/**
 * Data pipeline: reads the extracted pilgrim records in data/ and produces the
 * derived artefacts the site consumes, in static/data/ (gitignored, rebuilt on
 * every dev/build run).
 *
 * Outputs:
 *   static/data/pilgrims.json
 *   static/data/places-{faxian|xuanzang|yijing}.geojson
 *   static/data/routes.geojson           (firsthand stops only — hearsay places
 *                                         were reported, not visited, so the
 *                                         route line must not pass through them)
 *   static/data/regions.geojson          (fuzzy testimony zones from data/regions.source.json)
 *   static/data/observations.json        (Yijing's claims keyed to region ids)
 *   static/data/details.json             (canonicalId -> canonical record + full visits)
 *   static/data/journeys/{pilgrim}.json  (scrolly manuscripts)
 *   src/lib/data/labels.ts               (generated label/colour module)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { estimateMonksFromText } from '../src/lib/data/monkEstimates.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(root, 'data');
const OUT = join(root, 'static', 'data');
mkdirSync(join(OUT, 'journeys'), { recursive: true });

const read = (p) => JSON.parse(readFileSync(join(DATA, p), 'utf8'));
const write = (p, v) => writeFileSync(join(OUT, p), JSON.stringify(v));

const pilgrims = read('pilgrims.json');
const labels = read('labels.json');
const canonical = read('canonical/places.json');
const observationsRaw = read('yijing/observations.json');
const regionsSource = read('regions.source.json');
const sources = {
	faxian: read('faxian/places.json'),
	xuanzang: read('xuanzang/places.json'),
	yijing: read('yijing/places.json')
};

/* ---------------------------------------------------------------- labels --- */

// places.json stores yana WITH diacritics; sect as ASCII keys. Normalise both
// directions via the labels file.
const yanaDisplayToKey = Object.fromEntries(
	Object.entries(labels.yana).map(([key, display]) => [display, key])
);
const toYanaKey = (v) => yanaDisplayToKey[v] ?? (labels.yana[v] ? v : 'unknown');

// Colours live in src/lib/data/colours.ts (hand-owned, NEVER generated) —
// this script only generates labels and names.
const labelsTs = `// GENERATED by scripts/build-data.mjs — do not edit by hand.
// (Colours are hand-owned in ./colours.ts — edit them there.)

export const YANA_LABELS: Record<string, string> = ${JSON.stringify(
	{ ...labels.yana, mixed: 'Mahāyāna & Śrāvakayāna together' },
	null,
	'\t'
)};

export const SECT_LABELS: Record<string, string> = ${JSON.stringify(labels.sect, null, '\t')};

export const PILGRIM_NAMES: Record<string, string> = ${JSON.stringify(
	Object.fromEntries(pilgrims.map((p) => [p.id, p.name])),
	null,
	'\t'
)};
`;
writeFileSync(join(root, 'src', 'lib', 'data', 'labels.ts'), labelsTs);

/* ------------------------------------------------------------ enrichment --- */

const canonicalById = new Map(canonical.map((c) => [c.canonicalId, c]));

// Effective year: the 3 entries with null date.year get a value interpolated
// from their sequence neighbours, flagged so the UI can say "estimated".
function effectiveYears(entries) {
	const years = entries.map((e) => e.date?.year ?? null);
	return years.map((y, i) => {
		if (y !== null) return { year: y, interpolated: false };
		let prev = null;
		for (let j = i - 1; j >= 0; j--) if (years[j] !== null) { prev = years[j]; break; }
		let next = null;
		for (let j = i + 1; j < years.length; j++) if (years[j] !== null) { next = years[j]; break; }
		const year = prev !== null && next !== null ? Math.round((prev + next) / 2) : (prev ?? next);
		return { year, interpolated: true };
	});
}

function primaryYanaKey(yanaKeys) {
	const set = new Set(yanaKeys);
	if (set.has('Mahayana') && set.has('Sravakayana')) return 'mixed';
	if (set.has('Mahayana')) return 'Mahayana';
	if (set.has('Sravakayana')) return 'Sravakayana';
	if (set.has('Vajrayana')) return 'Vajrayana';
	if (set.has('non-Buddhist')) return 'non-Buddhist';
	return 'unknown';
}

const HOLY_TYPES = new Set(['holy-site', 'monastery', 'stupa-site']);

/**
 * Derived sect attributions (site by site, per Yijing obs-016's own warning
 * against blanket relabelling). Li Rongxi's and Legge's translations write
 * plain "Sarvāstivāda"; Yijing's regional testimony lets us add the
 * Mūlasarvāstivāda at specific sites:
 *  - Magadha: obs-001 (Sarvāstivāda flourishes most) + obs-019/020 (the
 *    tradition I-tsing practised there for ten years IS the Mūlasarvāstivāda)
 *  - Northern India: obs-003 (almost all Sarvāstivāda)
 *  - Nālandā: obs-020 directly (Xuanzang names no school there)
 * Deliberately EXCLUDED: the Tarim oases (obs-016 ties them to the older
 * Daśādhyāya Sarvāstivāda, "not identical"), Udyāna/Karashahr/Khotan
 * (obs-017: only the three subdivision schools), Pārsa (hearsay Persia) and
 * western India (Sāṃmitīya country). The pilgrims' own words in details.json
 * are never altered — this only enriches the map-filter layer, flagged in
 * `sectDerived`.
 */
const DERIVED_SECTS = {
	pataliputra: ['Mulasarvastivada'],
	'kapotaka-cluster': ['Mulasarvastivada'],
	iranaparvata: ['Mulasarvastivada'],
	matipura: ['Mulasarvastivada'],
	cinabhukti: ['Mulasarvastivada'],
	kanyakubja: ['Mulasarvastivada'],
	kasmira: ['Mulasarvastivada'],
	nalanda: ['Mulasarvastivada']
};

/**
 * Derived yāna attribution (site by site, never blanket — same pattern as
 * DERIVED_SECTS). No pilgrim writes "Vajrayāna": in their era it was an
 * esoteric lineage transmitted inside Mahāyāna communities, becoming public
 * only in the century after Yijing. But the records carry early traces of its
 * mantra practice, and at the two sites below — both openly Vajrayāna within
 * roughly a century — the map adds a derived Vajrayāna:
 *  - udyana: Xuanzang (Fascicle III) found a Mahāyāna country whose people
 *    "take the recitation of spells as their profession" and whose monks are
 *    "specially adept in reciting incantations". Udyāna is the Oḍḍiyāna of
 *    Vajrayāna tradition (Padmasambhava's homeland); openly Vajrayāna rock
 *    sculpture appears in Swat in the 7th–8th c. (Filigenzi 2015).
 *  - nalanda: Yijing himself "regularly went to the altar" at Nālandā trying
 *    to master the esoteric Vidyādhara-piṭaka (Kao Seng Chuan, biography of
 *    Tao-lin); under the Pālas Nālandā taught Vajrayāna openly, and its
 *    excavated bronzes (8th c. onward) include Vajrayāna deities.
 * Gate: applied only to entries whose own extracted yana includes the
 * Mahāyāna — so Faxian's Śrāvakayāna Udyāna of 403 CE stays untouched. Never
 * the bubble colour (yanaKey stays as witnessed); it joins yanaAll (the field
 * layer) and is flagged in `yanaDerived`. Full argument + references: /about.
 * Deliberately EXCLUDED: Dhānakaṭaka — despite the Vajrapāṇi-dhāraṇī story
 * and the later Kālacakra tradition there, its recorded community is
 * Mahāsāṃghika (Śrāvakayāna), so it fails the Mahāyāna gate.
 */
const DERIVED_YANAS = {
	udyana: ['Vajrayana'],
	nalanda: ['Vajrayana']
};

function derivedYanas(entry) {
	const keys = entry.yana.map(toYanaKey);
	if (!keys.includes('Mahayana')) return [];
	return (DERIVED_YANAS[entry.canonicalId] ?? []).filter((y) => !keys.includes(y));
}

function estimateMonks(monks) {
	if (monks?.count != null) return { monks: monks.count, monksEstimated: false };
	const estimate = estimateMonksFromText(monks?.text);
	if (estimate !== null) return { monks: estimate, monksEstimated: true };
	return { monks: null, monksEstimated: false };
}

function leanStop(entry, yearInfo) {
	const yanaAll = entry.yana.map(toYanaKey);
	const pilgrimCount = canonicalById.get(entry.canonicalId)?.pilgrimCount ?? 1;
	const coords = entry.scholarlyNotes.coordinates;
	const sectDerived = (DERIVED_SECTS[entry.canonicalId] ?? []).filter(
		(s) => !entry.sect.includes(s)
	);
	const yanaDerived = derivedYanas(entry);
	const { monks, monksEstimated } = estimateMonks(entry.monks);
	return {
		id: entry.id,
		canonicalId: entry.canonicalId,
		pilgrim: entry.pilgrim.toLowerCase(),
		sequence: entry.sequence,
		name: entry.names.primary,
		year: yearInfo.year,
		yearInterpolated: yearInfo.interpolated,
		// yanaKey (bubble colour) stays as witnessed; derived yānas join only
		// yanaAll (field layer) and are flagged separately.
		yanaKey: primaryYanaKey(yanaAll),
		yanaAll: [...yanaAll, ...yanaDerived],
		yanaDerived,
		sectKeys: [...entry.sect, ...sectDerived],
		sectDerived,
		typePrimary: entry.type[0] ?? 'other',
		types: entry.type,
		geoConfidence: entry.scholarlyNotes.geoConfidence ?? 'unknown',
		firsthand: entry.firsthand,
		monks,
		monksEstimated,
		monksText: entry.monks?.text ?? null,
		monasteries: entry.monasteries?.count ?? null,
		modernName: entry.scholarlyNotes.modernName ?? null,
		hasAnecdotes: entry.anecdotes.length > 0,
		anecdoteCount: entry.anecdotes.length,
		featured:
			entry.anecdotes.length > 0 || pilgrimCount >= 2 || entry.type.some((t) => HOLY_TYPES.has(t)),
		pilgrimCount,
		lon: coords.lon,
		lat: coords.lat
	};
}

const stopsByPilgrim = {};
for (const [pid, entries] of Object.entries(sources)) {
	const years = effectiveYears(entries);
	stopsByPilgrim[pid] = entries.map((e, i) => leanStop(e, years[i]));
}

/* --------------------------------------------------------------- places --- */

for (const [pid, stops] of Object.entries(stopsByPilgrim)) {
	write(`places-${pid}.geojson`, {
		type: 'FeatureCollection',
		features: stops.map(({ lon, lat, ...properties }) => ({
			type: 'Feature',
			geometry: { type: 'Point', coordinates: [lon, lat] },
			properties
		}))
	});
}

/* --------------------------------------------------------------- routes --- */

const toRad = (d) => (d * Math.PI) / 180;
function haversineKm(a, b) {
	const dLat = toRad(b[1] - a[1]);
	const dLon = toRad(b[0] - a[0]);
	const h =
		Math.sin(dLat / 2) ** 2 +
		Math.cos(toRad(a[1])) * Math.cos(toRad(b[1])) * Math.sin(dLon / 2) ** 2;
	return 6371 * 2 * Math.asin(Math.sqrt(h));
}

// Great-circle interpolation (spherical linear interpolation between two
// lon/lat points) so long sea legs curve plausibly instead of slicing
// straight across the projection.
function greatCirclePoints(a, b, n) {
	const φ1 = toRad(a[1]), λ1 = toRad(a[0]), φ2 = toRad(b[1]), λ2 = toRad(b[0]);
	const δ = 2 * Math.asin(
		Math.sqrt(
			Math.sin((φ2 - φ1) / 2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin((λ2 - λ1) / 2) ** 2
		)
	);
	if (δ === 0) return [a, b];
	const pts = [];
	for (let i = 0; i <= n; i++) {
		const f = i / n;
		const A = Math.sin((1 - f) * δ) / Math.sin(δ);
		const B = Math.sin(f * δ) / Math.sin(δ);
		const x = A * Math.cos(φ1) * Math.cos(λ1) + B * Math.cos(φ2) * Math.cos(λ2);
		const y = A * Math.cos(φ1) * Math.sin(λ1) + B * Math.cos(φ2) * Math.sin(λ2);
		const z = A * Math.sin(φ1) + B * Math.sin(φ2);
		pts.push([(Math.atan2(y, x) * 180) / Math.PI, (Math.atan2(z, Math.sqrt(x * x + y * y)) * 180) / Math.PI]);
	}
	return pts;
}

const routeFeatures = [];
for (const [pid, stops] of Object.entries(stopsByPilgrim)) {
	const onRoute = stops.filter((s) => s.firsthand);
	for (let i = 0; i < onRoute.length - 1; i++) {
		const a = onRoute[i];
		const b = onRoute[i + 1];
		const from = [a.lon, a.lat];
		const to = [b.lon, b.lat];
		const km = haversineKm(from, to);
		if (km < 1) continue;
		const n = Math.max(2, Math.min(64, Math.round(km / 50)));
		routeFeatures.push({
			type: 'Feature',
			geometry: { type: 'LineString', coordinates: greatCirclePoints(from, to, n) },
			properties: {
				pilgrim: pid,
				seq: i,
				fromId: a.id,
				toId: b.id,
				fromYear: a.year,
				toYear: b.year
			}
		});
	}
}
write('routes.geojson', { type: 'FeatureCollection', features: routeFeatures });

/* -------------------------------------------------------------- regions --- */

// Fuzzy testimony zones: data/regions.source.json defines semantic ellipses
// (centre + radii); geometry is generated. Deliberately loose and rounded —
// these are zones of testimony, not borders.
function ellipsePolygon({ center, rx, ry, rotation = 0 }, n = 24) {
	const rot = toRad(rotation);
	const ring = [];
	for (let i = 0; i <= n; i++) {
		const t = (i / n) * 2 * Math.PI;
		// slight organic wobble, deterministic per vertex
		const w = 1 + 0.06 * Math.sin(3 * t + rx) + 0.04 * Math.cos(5 * t + ry);
		const x = rx * w * Math.cos(t);
		const y = ry * w * Math.sin(t);
		ring.push([
			+(center[0] + x * Math.cos(rot) - y * Math.sin(rot)).toFixed(3),
			+(center[1] + x * Math.sin(rot) + y * Math.cos(rot)).toFixed(3)
		]);
	}
	ring[ring.length - 1] = ring[0];
	return [ring];
}

write('regions.geojson', {
	type: 'FeatureCollection',
	features: regionsSource.regions.map((r) => ({
		type: 'Feature',
		geometry: { type: 'Polygon', coordinates: ellipsePolygon(r) },
		properties: { id: r.id, name: r.name, label: r.label }
	}))
});

/* --------------------------------------------------------- observations --- */

const obs = observationsRaw.map((o) => ({
	id: o.id,
	topic: o.topic,
	region: o.region,
	regionIds: regionsSource.observationRegionMap[o.region] ?? [],
	claim: o.claim,
	yana: (o.yana ?? []).map(toYanaKey),
	sect: o.sect ?? [],
	source: o.source
}));
write('observations.json', obs);

/* -------------------------------------------------------------- details --- */

const entryById = new Map(
	Object.values(sources).flatMap((entries) => entries.map((e) => [e.id, e]))
);
const details = {};
for (const c of canonical) {
	details[c.canonicalId] = {
		canonical: c,
		visits: c.visitedBy
			.map((v) => entryById.get(v.placeId))
			.filter(Boolean)
			// The entry itself (the pilgrim's words) is never altered; the
			// derived yāna rides alongside, flagged, for the detail panel.
			.map((e) => {
				const yd = derivedYanas(e);
				return yd.length ? { ...e, yanaDerived: yd } : e;
			})
			.sort((a, b) => (a.date?.year ?? 0) - (b.date?.year ?? 0))
	};
}
write('details.json', details);

/* ------------------------------------------------------------- pilgrims --- */

write('pilgrims.json', pilgrims);

/* ------------------------------------------------------------- journeys --- */

const ROMAN = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'];
const XUANZANG_TITLES = {
	I: 'Across the deserts and oases — Agni to Kāpiśī',
	II: 'Entering India — Lampā to Gandhāra',
	III: 'The northern valleys — Udyāna to Rājapura',
	IV: 'Into the Middle Country — Ṭakka to Kapitha',
	V: 'Kanyākubja and the Ganges plain',
	VI: 'In the Buddha’s footsteps — Śrāvastī to Kuśinagara',
	VII: 'Bārāṇasī to Nepāla',
	VIII: 'Magadha — Bodh Gayā and the holy heartland',
	IX: 'Magadha — Nālandā and the hills of Rājagṛha',
	X: 'East and south — Īraṇaparvata to Malakūṭa',
	XI: 'The western kingdoms — Siṃhala to Varṇu',
	XII: 'The road home — Jāguḍa to Gostana'
};

function chapterise(pid, stops, defs) {
	return defs.map((d, i) => {
		const chapterStops = stops.filter(d.match);
		const lons = chapterStops.map((s) => s.lon);
		const lats = chapterStops.map((s) => s.lat);
		const bbox = [
			Math.min(...lons) - 1.5,
			Math.min(...lats) - 1.5,
			Math.max(...lons) + 1.5,
			Math.max(...lats) + 1.5
		];
		return {
			id: `${pid}-ch${i + 1}`,
			title: d.title,
			bbox,
			stops: chapterStops.map((s) => ({
				...s,
				camera: {
					center: [s.lon, s.lat],
					zoom: ['country', 'kingdom', 'region'].includes(s.typePrimary) ? 6 : 7.2
				}
			}))
		};
	});
}

const seqIn = (a, b) => (s) => s.sequence >= a && s.sequence <= b;

const journeyDefs = {
	faxian: [
		{ title: 'Leaving Chang’an — across the river of sand', match: seqIn(1, 5) },
		{ title: 'The Tarim oases', match: seqIn(6, 11) },
		{ title: 'Over the Onion Mountains into North India', match: seqIn(12, 17) },
		{ title: 'Purushapura and the Little Snowy Mountains', match: seqIn(18, 23) },
		{ title: 'The Middle Country', match: seqIn(24, 31) },
		{ title: 'The Buddha’s homeland', match: seqIn(32, 37) },
		{ title: 'Magadha — the holy heartland', match: seqIn(38, 45) },
		{ title: 'To the sea and home', match: seqIn(46, 53) }
	],
	xuanzang: ROMAN.map((numeral) => ({
		title: `Fascicle ${numeral} — ${XUANZANG_TITLES[numeral]}`,
		match: (s) => {
			const entry = entryById.get(s.id);
			const m = entry.source.ref.match(/^Fascicle ([IVX]+)/);
			return m?.[1] === numeral;
		}
	})),
	yijing: [
		{ title: 'The Southern Sea — Canton to the Nicobars', match: seqIn(1, 4) },
		{ title: 'India — Nālandā and the holy circuit', match: seqIn(5, 13) }
	]
};

for (const [pid, defs] of Object.entries(journeyDefs)) {
	const stops = stopsByPilgrim[pid];
	const p = pilgrims.find((x) => x.id === pid);
	const chapters = chapterise(pid, stops, defs);
	// Story-card payload: activity + best anecdote, pulled from the full entry
	// so the scrolly page needs no second fetch.
	for (const ch of chapters) {
		for (const s of ch.stops) {
			const entry = entryById.get(s.id);
			s.activity = entry.activity ?? null;
			s.quote = entry.source.quote;
			s.ref = entry.source.ref;
			s.bestAnecdote = entry.anecdotes[0]
				? { title: entry.anecdotes[0].title, kind: entry.anecdotes[0].kind, summary: entry.anecdotes[0].summary }
				: null;
		}
	}
	const total = chapters.reduce((n, c) => n + c.stops.length, 0);
	if (total !== stops.length) {
		throw new Error(`${pid}: chapters cover ${total} of ${stops.length} stops`);
	}
	write(`journeys/${pid}.json`, {
		pilgrim: pid,
		name: p.name,
		years: p.journey,
		bio: p.bio,
		sourceWork: p.source,
		chapters
	});
}

/* ------------------------------------------------------------- summary --- */

const counts = Object.entries(stopsByPilgrim)
	.map(([p, s]) => `${p}: ${s.length}`)
	.join(', ');
console.log(`build-data: ${counts}; ${routeFeatures.length} route segments; ${canonical.length} canonical places; ${obs.length} observations.`);
