// GENERATED by scripts/build-data.mjs — do not edit by hand.
// (Colours are hand-owned in ./colours.ts — edit them there.)

export const YANA_LABELS: Record<string, string> = {
	"Mahayana": "Mahāyāna",
	"Sravakayana": "Śrāvakayāna",
	"Vajrayana": "Vajrayāna",
	"non-Buddhist": "non-Buddhist",
	"unknown": "unknown",
	"mixed": "Mahāyāna & Śrāvakayāna together"
};

export const SECT_LABELS: Record<string, string> = {
	"Sarvastivada": "Sarvāstivāda",
	"Mulasarvastivada": "Mūlasarvāstivāda",
	"Sthavira": "Sthavira (Theravāda)",
	"Theravada": "Theravāda",
	"Sammitiya": "Sāṃmitīya",
	"Mahasamghika": "Mahāsāṃghika",
	"Dharmaguptaka": "Dharmaguptaka",
	"Mahisasaka": "Mahīśāsaka",
	"Kasyapiya": "Kāśyapīya",
	"Lokottaravada": "Lokottaravāda",
	"Mahavihara": "Mahāvihāra",
	"Abhayagiri": "Abhayagiri"
};

export const PILGRIM_NAMES: Record<string, string> = {
	"faxian": "Faxian",
	"xuanzang": "Xuanzang",
	"yijing": "Yijing"
};
